const ADMIN_EMAIL="hadhoahmed@gmail.com",ADMIN_PASS="GameNova@2026";
function adminLogin(){if(adminEmail.value===ADMIN_EMAIL&&adminPass.value===ADMIN_PASS){sessionStorage.setItem("gn_admin","1");showPanel()}else alert("بيانات الإدارة غير صحيحة")}
function showPanel(){gate.style.display="none";panel.style.display="block";render()}
function logoutAdmin(){sessionStorage.removeItem("gn_admin");location.reload()}
function products(){return JSON.parse(localStorage.getItem("gn_products")||"null")||[
{id:1,name:"PlayStation 5 Controller",cat:"ps",price:3499,icon:"🎮"},{id:2,name:"Gaming Headset",cat:"pc",price:1299,icon:"🎧"},{id:3,name:"Xbox Wireless Controller",cat:"xbox",price:2799,icon:"🕹️"},{id:4,name:"Mechanical Keyboard",cat:"pc",price:1899,icon:"⌨️"},{id:5,name:"Gaming Mouse",cat:"pc",price:899,icon:"🖱️"},{id:6,name:"PlayStation Gift Card",cat:"ps",price:500,icon:"💳"},{id:7,name:"Xbox Gift Card",cat:"xbox",price:500,icon:"💚"},{id:8,name:"RGB Desk Setup",cat:"pc",price:2399,icon:"✨"}]}
function render(){let ps=products(),us=JSON.parse(localStorage.getItem("gn_users")||"[]"),os=JSON.parse(localStorage.getItem("gn_orders")||"[]");pcount.textContent=ps.length;ucount.textContent=us.length;ocount.textContent=os.length;revenue.textContent=money(os.reduce((s,o)=>s+o.total,0));productRows.innerHTML=ps.map(p=>`<tr><td>${p.icon} ${p.name}</td><td>${p.cat}</td><td>${money(p.price)} ج.م</td><td><button class="danger" onclick="delProduct(${p.id})">حذف</button></td></tr>`).join("");orderRows.innerHTML=os.length?os.map((o,i)=>`<tr><td>${o.id}</td><td>${o.name}<br><small>${o.email}</small></td><td>${money(o.total)} ج.م</td><td><select onchange="status(${i},this.value)">${["جديد","قيد التجهيز","تم الشحن","مكتمل","ملغي"].map(s=>`<option ${s===o.status?"selected":""}>${s}</option>`).join("")}</select></td><td><button class="danger" onclick="delOrder(${i})">حذف</button></td></tr>`).join(""):"<tr><td colspan=5>لا توجد طلبات</td></tr>";userRows.innerHTML=us.length?us.map((u,i)=>`<tr><td>${u.name}</td><td>${u.email}</td><td>${u.date||"-"}</td><td><button class="danger" onclick="delUser(${i})">حذف</button></td></tr>`).join(""):"<tr><td colspan=4>لا يوجد مستخدمون</td></tr>"}
function money(n){return new Intl.NumberFormat("ar-EG").format(n)}
productForm.onsubmit=e=>{e.preventDefault();let ps=products();ps.push({id:Date.now(),name:pname.value,price:Number(pprice.value),cat:pcat.value,icon:picon.value||"🎮"});localStorage.setItem("gn_products",JSON.stringify(ps));e.target.reset();picon.value="🎮";render()}
function delProduct(id){let ps=products().filter(p=>p.id!==id);localStorage.setItem("gn_products",JSON.stringify(ps));render()}
function status(i,s){let os=JSON.parse(localStorage.getItem("gn_orders")||"[]");os[i].status=s;localStorage.setItem("gn_orders",JSON.stringify(os));render()}
function delOrder(i){let os=JSON.parse(localStorage.getItem("gn_orders")||"[]");os.splice(i,1);localStorage.setItem("gn_orders",JSON.stringify(os));render()}
function delUser(i){let us=JSON.parse(localStorage.getItem("gn_users")||"[]");us.splice(i,1);localStorage.setItem("gn_users",JSON.stringify(us));render()}
if(sessionStorage.getItem("gn_admin")==="1")showPanel();